### ISSUE TITLE
"Java not found" error message is misleading when JDK version != 11

### ISSUE THREAD

**Issue by agdespopoulos** [wpilibsuite/vscode-wpilib#100]
Ran into this myself when trying to get the extension running, but under JDK 8 instead of 11.

The extension logs "Java not found. Might have compilation errors" when the JDK cannot be found. However, even when `javac` can be found, but doesn't pass the test of being version 11, the same error message is printed, which is misleading.

I'd be happy to fix it myself, but I'm not sure the appropriate place to put an error about JDK version not being correct, as jdkdetector.ts doesn't print any error messages and that information is lost by the time it makes it to extension.ts.

**Comment by ThadHouse** [comment]
I'll fix the warning to be clearer, but please do not be using the Beta unless you are a beta team. If you are trying to test out please use the Alpha. The beta build has some issues, and was for internal testing only.

**Comment by agdespopoulos** [comment]
My bad, turns out I'm bad at reading, specifically sentences like "Do not use this if you are not a WPILib developer.". Thanks for calling that out, I'll switch to Alpha now.

Thanks!

**Comment by cfernan62** [comment]
Hello,

I am using Alpha version of Visual Studio Code with wpilib extension.  I'm getting this error when I try to create a new project:   Java 11 required, but not found.  Might have compilition errors.


![visualstudiocode](https://user-images.githubusercontent.com/25114299/47450990-a0572f00-d794-11e8-9ff7-3e044993bca9.png)
![visualstudiocode_error](https://user-images.githubusercontent.com/25114299/47450991-a0efc580-d794-11e8-99b6-15aa8ca4061e.png)


Thanks for your assistance!

**Comment by ThadHouse** [comment]
That means you are not using the alpha, but instead grabbed the beta. Uninstall the version from your vs code and grab the alpha from the release page, not the beta.

**Comment by cfernan62** [comment]
Thanks Thad!  I must have snagged the wrong .vsix file by mistake.
