### ISSUE TITLE
New Project Creator silently fails to populate new project directory

### ISSUE THREAD

**Issue by chauser** [wpilibsuite/vscode-wpilib#102]
If the box below the prompt "select a folder to place the new project into" is populated with a relative path then the creator only creates the folders (that one and one with the project name inside it). It does not set up the actual project files inside the project folder and it does not prompt to open the new project.
This behavior seen on linux with the latest vscode-wpilib alpha version. I believe it does not depend on whether the "create new folder"  box is checked. I've tried it for C++; I don't know if it works this way for Java projects. If the first box is populated with a full path then the folders are created and populated as expected.

**Comment by ThadHouse** [comment]
Hmm I had never tested with relative paths. I'll actually update it to completely disallow relative paths for that, since the working directory of vscode is not deterministic. Thanks!

**Comment by ThadHouse** [comment]
I added an error that pops up when a relative path is entered.
