### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by idoavny** [wpilibsuite/vscode-wpilib#104]
it says that gradlew couldnt find javar/home. what do i do?

**Comment by idoavny** [comment]
its the same problems with examples

**Comment by ThadHouse** [comment]
javar is not something I've heard of. Can you send the full error output?

**Comment by idoavny** [comment]
i tried to remember what it says it was like this "Error: Unable to access jarfile /home/lvuser/FRC/"

**Comment by ThadHouse** [comment]
Ah. Are you creating a project with a space in the name? That doesn't work in the alpha. It has been fixed for the season.

If not, I'm going to need more info, like a zip of your project and the full error output.

**Comment by idoavny** [comment]
yea the project had space in it, i just changed it.
