### ISSUE TITLE
Java error checking

### ISSUE THREAD

**Issue by cjdenio** [wpilibsuite/vscode-wpilib#106]
Hi,
After creating a new Java project, VS Code makes no attempt to check for errors. I am free to misspell class names. After I run "Debug Robot Code", however, it starts working perfectly. It would be nice if the documentation mentioned this. Am I missing something?
Errors or not, I love getting to use VS Code instead of Eclipse. This is a major improvement, and thank you for all of the work you do.

Upon closer inspection, it has something to do with starting the "Java Language Server". During that initial "Debug Robot Code", and after creating a project, the lower-left corner displayed "Starting Java Language Server".

**Comment by ThadHouse** [comment]
What's actually happening is gradle is actually downloading all of the dependencies, trying to get everything needed for intellisense. Why it shows up after the build is that the build will not finish before the VS Code dependency downloads get finished. Likely, that first build took a long time, and builds int the future will be much faster.

For the season release, we grab less dependencies during the configuration phase to make this less of an issue.

**Comment by cjdenio** [comment]
Ok. So a build is required to download these dependencies? Thank you!

**Comment by ThadHouse** [comment]
No, VS Code was downloading them in the background, but it won't get intellisense until that download finishes. Running the build just waited for that download to finish. So it looks like that solved it, but not exactly.

**Comment by cjdenio** [comment]
Ok, thank you! That cleared up some things. I can't wait to start using Visual Studio on an actual robot 😄
