### ISSUE TITLE
Shuffleboard Launch Issues

### ISSUE THREAD

**Issue by spencers0730** [wpilibsuite/vscode-wpilib#110]
Not sure this is the correct place to post, but when I run:
`./gradlew shuffleboard`
I get a confirmation of build success within VSCode terminal, but the jar does not launch.  I have checked
`java -version`
which is 11.0.1 LTS, and I have refreshed gradle dependencies with
`./gradlew build --refresh-dependencies`
I am running v2019.0.0-alpha-4, since the beta had some issues detecting Java, and I have also refreshed and tested this on multiple test projects. What am I missing?

**Comment by AustinShalit** [comment]
Are you a member of a [beta team](https://www.firstinspires.org/sites/default/files/uploads/frc/Blog/2019/2019-beta-teams.pdf)?  If not, you should only use the alpha and Java 8.

**Comment by spencers0730** [comment]
Thank you; it was actually an issue with having both Java 8 and JDK 11.
