### ISSUE TITLE
ToolsUpdater.sh script on Mac

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/vscode-wpilib#116]
The line endings are in dos format on ToolsUpdater.sh on mac after decompressing and untaring the file. dos2unix is not available on macs by default. Also, realpath is missing. Rumor is we're considering switching to python or ruby. The installed versions with Mojave are:

python 2.7 (installed by default and you can get 3 with homebrew)
and ruby 2.3.7

**Comment by AustinShalit** [comment]
This issue was moved to wpilibsuite/WPILibInstaller#11

**Comment by bradamiller** [comment]
in Beta 2 I needed to run dos2unix on the ToolsUpdater.sh file.
