### ISSUE TITLE
New class/cmd doesn't work from the cmd-shift-p menu

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/vscode-wpilib#121]
Selecting a folder in a project (commands), then cmd-shift-p "New class/command" item seems to always give the error "Must select a folder". If I right-click on the same folder and select "New class/command" it works great. In fact, it's really nice!

**Comment by ThadHouse** [comment]
This is not a bug, it's an intentional feature. There is no good UI to select a folder from a command, so I would have no idea where to put the new command. 

I'm going to hide that command from the palette for beta 2.

**Comment by bradamiller** [comment]
Makes sense.
