### ISSUE TITLE
Dumb Question - Java versions

### ISSUE THREAD

**Issue by spencers0730** [wpilibsuite/vscode-wpilib#122]
So for Shuffleboard you need JavaFX, and for vscode-wpilib you need Java 11, but I have not found how to get Java 11 with JavaFX. I've tried OpenJDK JFX jmods and the SDK, but to no avail on MacOS. If you have any suggestions, please let me know.

**Comment by ThadHouse** [comment]
The tools for 2019 include javafx. The alpha still requires Java 8 though.

For javafx after 10, the application has to include javafx. Our tools built for 2019 do this.

**Comment by spencers0730** [comment]
So I guess my issue is that I cannot run `./gradlew shuffleboard` or `./gradlew smartdashboard` with all combinations of Java 8, Java 11, and the beta or alpha version of the wpilib extension.

**Comment by ThadHouse** [comment]
Yup. Beta will require 11, and alpha will require 8.
