### ISSUE TITLE
Adding include paths to a project

### ISSUE THREAD

**Issue by bobwolff68** [wpilibsuite/vscode-wpilib#126]
I've been unable to build our last-years' project and am stuck early in the process as include files aren't being found by the compiler. 

As a simplified project, I started a new robot sample based on Arcade and then I've added a single #include directive to include a common header of ours hoping to get the include folders to work out in this simpler unit test...the common headers are in a completely separate folder.

The folder for the headers on my Mac is: "/Users/rwolff/dev/robotics/FRCTeam1967/code/include"

The full path folder (Mac) above contains a battery of common include headers needed by all of our projects. 

How do I tell the cross-compiler build system about directives for include file locations? Where should I set these? It seems it must be a gradle setting but I've tried several different ways and have begun to understand that there may be a need to do a 'wpilib refresh gradle C++ properties" to have it re-generate gradle items before doing a 'robot build' but still haven't gotten the right combination of things.

**Comment by ThadHouse** [comment]
The headers happen completely in the build.gradle file. In that file, you should have an `exporterHeaders` block. Inside of there add 

`srcDirs path/to/include/root`

That should enable building to see those headers. Then once you run the c++ refresh they should show there.

**Comment by ThadHouse** [comment]
Did this solve your problem? It should have. If if did great, if not comment here and I'll reopen.
