### ISSUE TITLE
C/C++ Google Testing

### ISSUE THREAD

**Issue by jython234** [wpilibsuite/vscode-wpilib#131]
Currently I see no instructions whatsoever for setting up a project to use Google Tests. In fact, I still can't figure out how to set it up correctly myself. The built in templates also do not generate projects that are set up for Google-test.

Apologies if I missed something and this shouldn't be an issue.

**Comment by ThadHouse** [comment]
If you're using the alpha, it's not setup for Google test, and is difficult to add. If you're using the beta, or the season release those have Google test already enabled.

**Comment by ThadHouse** [comment]
If this didn't solve your problem, please comment, but I'm going to close this to clean up issues.
