### ISSUE TITLE
Create new class/command does not create header guards. 

### ISSUE THREAD

**Issue by retrax24** [wpilibsuite/vscode-wpilib#133]
When a new file couple is made the #pragma one command is used instead of the header guards. Could an option be made to choose pragma once or header guards?

**Comment by ThadHouse** [comment]
It could be, but it would be very invasive to the generation code, for basically no benefit. Every compiler nowadays supports #pragma once, and its more reliable, especially compared to generation. Header guards are more error prone to collisions then pragma once, and we want things to be easier for users.

**Comment by ThadHouse** [comment]
After some more discussions, we definitely do not want to have multiple options, and #pragma once is much less error prone, so that is the one we are going to go with.
