### ISSUE TITLE
VSCode & Shuffleboard

### ISSUE THREAD

**Issue by RedThunder7166** [wpilibsuite/vscode-wpilib#141]
We are trying to open Shuffleboard via the Driver's Station while using VSCode.  The FIRST information about opening Shuffleboard does not work as there is no wpilib folder.  Any help?

**Comment by AustinShalit** [comment]
Are you using the alpha or the beta?

**Comment by RedThunder7166** [comment]
We are using the version 1.29.1

**Comment by ThadHouse** [comment]
Thats the VS Code version. What version of the WPILib extension?

**Comment by RedThunder7166** [comment]
2019.0.0-alpha-4

**Comment by ThadHouse** [comment]
You're using the alpha. It does not support opening tools, and does not install any. Eclipse is still needed for the tools for the 2018 DS.

**Comment by RedThunder7166** [comment]
Are they releasing tools for VSCode at the beginning of the 2019 season?

**Comment by ThadHouse** [comment]
Yes the 2019 release will include tools, and will work with the DriverStation.

**Comment by RedThunder7166** [comment]
Is there any way to test autonomous by entering game information without  shuffleboard?  We are learning java and trying to test last years autonomous on our bot.

**Comment by bradamiller** [comment]
I'm not what game information you want to enter. Shuffleboard is a good way of getting data to the robot by using widgets like the Sendable Chooser for choosing options or fields and reading values as they change.

**Comment by RedThunder7166** [comment]
All we want to do is enter game data into the program to test autonomous.  Can we use the labview dashboard to do that?  (LLL, RRR, RLR, LRL)

**Comment by RedThunder7166** [comment]
We also want to be able to select whether we are, for example, in postion 1, 2 or 3 on the field.

**Comment by RedThunder7166** [comment]
We want to be able to select a specific autonomous command for testing, but aren't sure if that is possible. Sorry that was unclear.

**Comment by AustinShalit** [comment]
You can enter the game data on the setup tab of the driver station: https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/826278-2018-game-data-details#testing-game-specific-data

You can use shuffleboard to select where you are starting with a sendable chooser: https://wpilib.screenstepslive.com/s/3120/m/7932/l/81109-choosing-an-autonomous-program-from-smartdashboard

**Comment by RedThunder7166** [comment]
@AustinShalit I don't think we can use Shuffleboard though.

**Comment by AustinShalit** [comment]
In order to download Shuffleboard you need to install the eclipse plugins (the 2018 IDE).  To do this follow the instructions here: https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/599679-installing-eclipse-c-java

This will be changing in 2019 though so look out for new instructions closer to kickoff.

**Comment by ThadHouse** [comment]
Since this issue is related to the alpha, and there has not been an update I'm going to close it. If you need further help please comment.
