### ISSUE TITLE
OpenJFX Incompatability

### ISSUE THREAD

**Issue by spencers0730** [wpilibsuite/vscode-wpilib#144]
So I am using PathWeaver (Java 11), Shuffleboard (Java 11), and  vscode-wpilib alpha 4 (Java 11). I am on MacoS, so I downloaded OpenJDK 11 from [here](https://jdk.java.net/11/). When I manually run Shuffleboard (i.e. the plain .jar) with `java -jar Shuffleboard.jar` or in a VSCode project with `./gradlew shuffleboard --stacktrace`, I get `java.lang.NoClassDefFoundError: javafx/application/Application`. Obviously, this is because OpenJFX no longer comes with OpenJDK. Unfortunately, it has been stated previously that JavaFX is bundled with the WPILib tools this year. I am just a bit confused as to what I am doing wrong.

**Comment by ThadHouse** [comment]
The alpha still requires Java 8. The Java 11 switch will happen for the season release.

**Comment by spencers0730** [comment]
So for now I cannot run any of the other tools?
