### ISSUE TITLE
Azure's build causes gradlew to be released as a CRLF file

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/vscode-wpilib#155]
Checkout as CRLF is the dumbest idea ever invented in a version control system.

**Comment by AustinShalit** [comment]
I do not think #156 fixed this completely.  Just like allwpilib, all files should be lf except those that we need to be crlf.

**Comment by ThadHouse** [comment]
@AustingShalit what release were you testing? The beta 4 doesn't have the fix in it.
