### ISSUE TITLE
Add open documentation task

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/vscode-wpilib#165]
We should create a task that will open the documentation in the user's web browser so they do not need to go hunting

**Comment by WuYuanhun** [comment]
Hello, could you please provide the documentation link
Thanks.

**Comment by WuYuanhun** [comment]
http://wpilib.screenstepslive.com/s/currentCS
this one?

**Comment by AustinShalit** [comment]
No, this one: http://first.wpi.edu/FRC/roborio/release/docs/java but the local directory, not the online one

**Comment by WuYuanhun** [comment]
See. Thanks

**Comment by WuYuanhun** [comment]
Could I describe this function as to store all docs on user's computer and open them in user's browser (like a offline docs)
or just open site page online 

or could be both?

**Comment by AustinShalit** [comment]
This would locate the documentation that already exists on the users computer (where they installed the resources like the JDK) and open it in the user's browser.
