### ISSUE TITLE
Set Java Home might have issues

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/vscode-wpilib#172]
There are spurious reports of that command failing because it can't set the setting properly. I need to debug this and make sure this is not an issue on our side.

**Comment by RazeLighter777** [comment]
Yes it is an issue for me. There is now a commit which will fix this that hasn't been merged yet.

**Comment by ThadHouse** [comment]
There is not a fixing commit for this yet. It's on my list to do.
