### ISSUE TITLE
Plugin on VSCode Marketplace

### ISSUE THREAD

**Issue by iboyperson** [wpilibsuite/vscode-wpilib#180]
This plugin has popped up on the VSCode Marketplace [here](https://marketplace.visualstudio.com/items?itemName=wpilibsuite.vscode-wpilib). I wanted to put this here as I am not sure weather this is official or not. The uploaders profile is blank which is what drove me to put this here as it seemed a little strange. Some confirmation as to weather this is official or not would be appreciated.

**Comment by ThadHouse** [comment]
Yes, that is the official one. I'll fill out our profile.

**Comment by sciencewhiz** [comment]
The known issues should be updated too, since this is no longer alpha
