### ISSUE TITLE
Vendor Library Doc

### ISSUE THREAD

**Issue by WuYuanhun** [wpilibsuite/vscode-wpilib#186]
Is there a doc about how to install Vendor Library? 
Confused when using ```WPILib: manage Vendor Library```, nothing happens.
Thanks

**Comment by ThadHouse** [comment]
You need to follow the individual vendor documents on how to install their libraries so that command can see them and install them into the project.

**Comment by WuYuanhun** [comment]
Thanks!
Also found the steps on
https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/682619-3 rd-party-libraries#adding-an-offline-installed-library
