### ISSUE TITLE
intel[ej

### ISSUE THREAD

**Issue by loopking** [wpilibsuite/vscode-wpilib#190]

**Comment by ThadHouse** [comment]
Please stop with these.

**Comment by loopking** [comment]
y close

**Comment by loopking** [comment]
Intellij has better features than visual sudio
It should be use for 2020

**Comment by ThadHouse** [comment]
Still not helpful, and a productive cohesive comment would go further as well.

**Comment by loopking** [comment]
[https://www.jetbrains.com/idea/](https://www.jetbrains.com/idea/)

Every aspect of IntelliJ IDEA is specifically designed to maximize developer productivity.

Together, the powerful static code analysis and ergonomic design make development not only productive but also an enjoyable experience.

Deep intelligence
After IntelliJ IDEA has indexed your source code, it offers a blazing fast and intelligent experience by giving relevant suggestions in every context: instant and clever code completion, on-the-fly code analysis, and reliable refactoring tools.

Out-of-the-box experience
Mission-critical tools such as integrated version control systems and a wide variety of supported languages and frameworks are all to hand — no plugin hassle included.

Smart code completion
While the basic completion suggests names of classes, methods, fields, and keywords within the visibility scope, the smart completion suggests only those types that are expected in the current context.

Framework-specific assistance
While IntelliJ IDEA is an IDE for Java, it also understands and provides intelligent coding assistance for a large variety of other languages such as SQL, JPQL, HTML, JavaScript, etc., even if the language expression is injected into a String literal in your Java code.

Productivity boosters
The IDE predicts your needs and automates the tedious and repetitive development tasks, so you can stay focused on the big picture.

Developer ergonomics
In every design and implementation decision that we make, we keep in mind the risk of interrupting the developer's flow and do our best to eliminate or minimize it.

The IDE follows your context and brings up the corresponding tools automatically.

Unobtrusive intelligence
The coding assistance in IntelliJ IDEA is not about only the editor: it helps you stay productive when dealing with other aspects as well: e.g. filling a field, searching over a list of elements; accessing a tool window; or toggling a setting, etc.

**Comment by SamCarlberg** [comment]
Several developers on the WPILib team use IntelliJ as our main IDE. We are familiar with its uses. Copy-and-pasting the marketing page for it is not an argument for its use in FRC; in particular, you have given no argument for why it would be more useful for FRC teams than the current VSCode setup we have now, nor a solution for the C++ teams for which IntelliJ will not work.

**Comment by SamCarlberg** [comment]
Given that the account that opened this issue was created just for that purpose, and given the discussion on the Discord chat about another issue with a similar title, this is clearly a troll
