### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by spencers0730** [wpilibsuite/vscode-wpilib#219]
Installed the latest vscode-wpilib and now when running `gradle build` or `./gradlew build`, I get:
```
An exception occurred applying plugin request [id: 'edu.wpi.first.GradleRIO', version: '2019.3.2']
> Failed to apply plugin [class 'jaci.gradle.deploy.DeployPlugin']
   > Could not create an instance of type jaci.gradle.deploy.DeployExtension.
      > java.lang.NullPointerException (no error message)
```

**Comment by ThadHouse** [comment]
When you updated, you didn't update the Gradle version to 5.2, did you? 5.2 is not compatible with gradlerio, you need to stay on 5.0. if that's not what happened, run ./gradlew build --scan and send the url it spits out. That will let us see where the error is coming from.

**Comment by spencers0730** [comment]
https://github.com/wpilibsuite/GradleRIO/issues/319
