### ISSUE TITLE
Cant upload to V14

### ISSUE THREAD

**Issue by Catalyst10120** [wpilibsuite/vscode-wpilib#224]
we just updated our Rio to the mandatory V14 can when we go to up load we get a version error saying we are running V14 but need V12 error message:

RoboRIO Image invalid! RoboRIO: 2019_v14, allowed: [2019_v12]

**Comment by ThadHouse** [comment]
You need to update to WPILib 2019.4.1 in order to deploy to image 14. The kickoff release will not upload to it.

**Comment by Catalyst10120** [comment]
whats the proper way to update when we did this we updated it by downloading the .vsix and installed it

**Comment by ThadHouse** [comment]
Installing the VSIX isn't enough to update. We recommend you follow the instructions here to run the newest version of the installer (it can run over the old one), and then it will prompt you to update your project.

https://github.com/wpilibsuite/allwpilib/releases
