### ISSUE TITLE
Check for WPILib updates doesn't show new version

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/vscode-wpilib#229]
If I install WPILib 2019.3.2 and then create a new project and then check for WPILib updates online, I get the following message, which doesn't show the new version to be installed.

![image](https://user-images.githubusercontent.com/4885091/56627353-411a9000-65fa-11e9-8164-a0d9ca0a21d7.png)

**Comment by ThadHouse** [comment]
What version of VS Code? I wonder if the updated electron in 1.31 changed this. Because on mine this shows correctly.

**Comment by sciencewhiz** [comment]
1.30.1

**Comment by ThadHouse** [comment]
Hmm interesting. And the installed vscode version is 2019.3.2?

**Comment by sciencewhiz** [comment]
Yes
