### ISSUE TITLE
"Java 11 required, but not found. Might have compilation errors" when JDK 11 is installed

### ISSUE THREAD

**Issue by tylertian123** [wpilibsuite/vscode-wpilib#235]
Every time I start VS Code, the extension tells me that "Java 11 required, but not found. Might have compilation errors". However, I do have JDK 11 installed. Here's the output of `java -version`:
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```
and `javac -version`:
```
javac 11.0.3
```
This problem has been around for a while now. I'm currently using version 2019.4.1 of the extension on VS Code 1.35.1 (and Insiders 1.36.0), running on Ubuntu 18.04.

**Comment by AustinShalit** [comment]
What is your JAVA_HOME environment variable set to?

**Comment by tylertian123** [comment]
You're right, it's unset. Setting it to `/usr/lib/jvm/java-1.11.0-openjdk-amd64` fixed the issue. Thanks!

**Comment by AustinShalit** [comment]
Sweet!

**Comment by GabrielDeml** [comment]
Just in case anyone runs into this problem again. Put this in /etc/profile and reboot. 

`export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")`
