### ISSUE TITLE
Splitting vscode package into @types/vscode and vscode-test

### ISSUE THREAD

**Issue by iboyperson** [wpilibsuite/vscode-wpilib#238]
VSCode is splitting the `vscode` package into `@types/vscode` and `vscode-test`. This project should likely be updated accordingly.

Refrences:
https://github.com/microsoft/vscode/issues/71048
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_36.md#splitting-vscode-package-into-typesvscode-and-vscode-test

**Comment by ThadHouse** [comment]
Thanks! I'll take a look at this in the next week or so.
