### ISSUE TITLE
Update/add menu options for new commandbased

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/vscode-wpilib#263]
VS Code needs to be updated for menu option that use the new commandbased API. Relies upon https://github.com/wpilibsuite/allwpilib/pull/1785 and https://github.com/wpilibsuite/allwpilib/pull/1682

**Comment by ThadHouse** [comment]
We don't actually need to do anything on the vscode side. The extension picks up those json files in that repo to get that information.
