### ISSUE TITLE
gradlew isn't chmod'd on macOS

### ISSUE THREAD

**Issue by JacisNonsense** [wpilibsuite/vscode-wpilib#28]

**Comment by AustinShalit** [comment]
Not closed by #29

**Comment by SamCarlberg** [comment]
Ditto for Linux

**Comment by ThadHouse** [comment]
Closed in https://github.com/wpilibsuite/vscode-wpilib/commit/b8ec2910533a92f8f72bf2113407e8d525e9b10f
