### ISSUE TITLE
Gradle Cache does not work

### ISSUE THREAD

**Issue by carbotaniuman** [wpilibsuite/vscode-wpilib#299]
From a discord convo.

**Comment by sciencewhiz** [comment]
What version of the extension? What version of gradlerio? What os? Is offline enabled?

**Comment by ThadHouse** [comment]
I broke it when I was updating to Gradle 6 in master. So it's not in a release yet, just broken in master currently.

**Comment by ThadHouse** [comment]
Fixed by #300
