### ISSUE TITLE
Add simulation GUI support in default build.gradle

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/vscode-wpilib#313]
We should include the simulation GUI in the default build.gradle file:

`simulation wpi.deps.sim.gui(wpi.platforms.desktop, false)`

**Comment by PeterJohnson** [comment]
The false should be true for C++.  C++ should also be conditionally enabled I think?

**Comment by ThadHouse** [comment]
No need for a conditional enable, it doesn't get linked to directly so it's fine there. The true is required though.
