### ISSUE TITLE
projectYear still shown as "Beta2020-2"

### ISSUE THREAD

**Issue by iboyperson** [wpilibsuite/vscode-wpilib#330]
In `.wpilib/wpilib_preferences.json` the property projectYear still shows as "Beta2020-2"

**Comment by ThadHouse** [comment]
Whoops. In the grand scheme of things, this doesn't matter. I'll fix it in the first patch release, but future versions will accept both, since it was a part of an official release.

**Comment by ThadHouse** [comment]
Closed by #332
