### ISSUE TITLE
Mac Simulation GUI does not launch first time

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/vscode-wpilib#334]
The first time a user attempts to launch the simulation GUI on macOS, the simulation will fail to load because the DYLD_LIBRARY_PATH & LD_LIBRARY_PATH environment variables are not set properly by the vscode-java-debug extension.

Workaround is to attempt to launch the simulation GUI a second time without closing the debug console from the first run.

Tracking upstream here: https://github.com/microsoft/vscode-java-debug/issues/742

**Comment by AustinShalit** [comment]
This looks like an issue in VS Code (https://github.com/microsoft/vscode-java-debug/issues/742#issuecomment-573282679).

Now tracking upstream here: https://github.com/microsoft/vscode/issues/88306

**Comment by AustinShalit** [comment]
This has been resolved in the Insiders Edition of Visual Studio Code. Once they push an official release we should be able to close this issue.

**Comment by ThadHouse** [comment]
We can't easily update in the installer, so this will need to stay open until at least after the season.

**Comment by AustinShalit** [comment]
Luckily (or maybe not) macOS doesn't have an installer

**Comment by AustinShalit** [comment]
The VS Code team has released the patch.
