### ISSUE TITLE
Interface Will Not Load

### ISSUE THREAD

**Issue by AriannaKerkmaz** [wpilibsuite/vscode-wpilib#362]
When I attempt to download the FRC version of VS Code, nothing appears in the window other than a black box. The application window will have areas with which I can interact and the prompts "Welcome" and "WPI Command Palette" appear when hovered over, but the window remains black apart from the mouse. Multiple attempts have been made at re-downloading, none have been successful.
I am using Windows 8.
What would be possible resolutions?

**Comment by AriannaKerkmaz** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/35197471/79602349-51a00200-80b8-11ea-960f-2297f2b13d3c.png)

**Comment by AustinShalit** [comment]
I have a few ideas to try and resolve that. First, can you please make sure your computer is up to date? You can do this by going to the "Update" page in settings. If you computer is up-to-date, you can try to disable gpu acceleration for VS Code. Right click on the "FRC VS Code 2020" shortcut on the desktop and choose Properties. Under the "Target" add `--disable-gpu` to the end of what is already there. Apply and close the change and then try to open VS Code again using the shortcut.

**Comment by AriannaKerkmaz** [comment]
Thank you! That worked!
