### ISSUE TITLE
Variable location of the wpilib directory?

### ISSUE THREAD

**Issue by TheAllSeeing** [wpilibsuite/vscode-wpilib#374]
From what I gather, this is impossible right now, and I while this doesn't seem to be bothering too many people, and is probably mostly a problem for Linux, I can personally attest having it stuck in my home directory without even the ability to hide it (since it would require renaming) was really frustrating.

**Comment by ThadHouse** [comment]
This has been discussed here. Any discussion should continue there.

https://github.com/wpilibsuite/allwpilib/issues/2073

There are many reasons why choosing a non hidden directory, and not allowing it to be moved was picked. It's extremely unlikely to be changed again, as its not worth the ecosystem pain for users who maybe are not as knowledgeable.
