### ISSUE TITLE
Generate Project produces error "Can only extract to absolute path" Source: WPILib (Extension)

### ISSUE THREAD

**Issue by wa4lmlQRT** [wpilibsuite/vscode-wpilib#378]
In WPILib Project Creator - Visual Studio Code, an error is generated when the "Generate Project" icon is selected. The error message is "Can only extract to absolute path". When the error message is expanded an additional line is presented "Source: WPILib (Extension)".

**Comment by ThadHouse** [comment]
That error message is correct. The path that you give to place the project must be an absolute path, not a relative path. What path exactly are you trying?

**Comment by wa4lmlQRT** [comment]
I checked the box that allows the WPILib Project Creator to create a folder for the project. Is there a step to specify the path prior to initiating Generate Project?Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Thad House <notifications@github.com> Date: 7/22/20  4:16 PM  (GMT-06:00) To: wpilibsuite/vscode-wpilib <vscode-wpilib@noreply.github.com> Cc: wa4lmlQRT <tevepauj@bellsouth.net>, Author <author@noreply.github.com> Subject: Re: [wpilibsuite/vscode-wpilib] Generate Project produces error "Can only extract to absolute path" Source: WPILib (Extension) (#378) 
That error message is correct. The path that you give to place the project must be an absolute path, not a relative path. What path exactly are you trying?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wpilibsuite/vscode-wpilib/issues/378#issuecomment-662700950",
"url": "https://github.com/wpilibsuite/vscode-wpilib/issues/378#issuecomment-662700950",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ThadHouse** [comment]
The folder specified by the "Select a folder to place the project into" is where the project will be placed, but that folder must be absolute (Start with either the drive letter on windows or / on linux). That box is not the project name.

**Comment by wa4lmlQRT** [comment]
Thanks!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Thad House <notifications@github.com> Date: 7/22/20  5:07 PM  (GMT-06:00) To: wpilibsuite/vscode-wpilib <vscode-wpilib@noreply.github.com> Cc: wa4lmlQRT <tevepauj@bellsouth.net>, Author <author@noreply.github.com> Subject: Re: [wpilibsuite/vscode-wpilib] Generate Project produces error "Can only extract to absolute path" Source: WPILib (Extension) (#378) 
The folder specified by the "Select a folder to place the project into" is where the project will be placed, but that folder must be absolute (Start with either the drive letter on windows or / on linux). That box is not the project name.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wpilibsuite/vscode-wpilib/issues/378#issuecomment-662721715",
"url": "https://github.com/wpilibsuite/vscode-wpilib/issues/378#issuecomment-662721715",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
