### ISSUE TITLE
Support old and new RobotBuilder

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/vscode-wpilib#391]
See: wpilibsuite/RobotBuilder#259 &  wpilibsuite/WPILibInstaller-Avalonia#25

Because RobotBuilder is going to be publishing both an old and a new version, the VS Code tool menu should launchl both versions with different names. That way teams can choose the version appropriate for them.

**Comment by ThadHouse** [comment]
This is actually 100% handled by https://github.com/wpilibsuite/WPILibInstaller-Avalonia/issues/25. Nothing will need to be done here at all. So closing this.
