### ISSUE TITLE
Guess command directory

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/vscode-wpilib#41]
It would kinda be nice to be able to create commands/subsystems from the command palette and have it guess which directory you want to put them in. It could probably just look for a directory under src named commands or subsystems.

**Comment by ThadHouse** [comment]
Since the same dialog creates both commands and subsystems, I think this would be more confusing. And I think we'd likely guess wrong more often then not.

**Comment by ThadHouse** [comment]
I think it's best to just disable that option from the command palette. VS Code doesn't have a fantastic folder picker, and it would get confusing otherwise.
