### ISSUE TITLE
Project Creator Auto Follow

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/vscode-wpilib#42]
Is it possible to have the project creator auto select the next option for me?  Right now my process is:
1. Click on project type
2. Select project type
3. click on lang
4. select lang
5. ....

I want it to be:
1. Click on project type
2. select project type
3. lang auto opens
4. select lang
5. ...

Of course it would only do this if the next option was not selected yet.

**Comment by ThadHouse** [comment]
I don't actually think we want to do this. The original setup was like this, and a few people during testing found it really confusing. Its easy to do, but I don't think its worth it.

**Comment by ThadHouse** [comment]
This actually works alot better with the new setup, so I'm actually OK with this change.
