### ISSUE TITLE
Java 2021 Project Import corrupts deploy binary files.

### ISSUE THREAD

**Issue by CoryNessCTR** [wpilibsuite/vscode-wpilib#421]
When importing a Java Project from 2020 to 2021, binary files in the deploy directory are corrupted. This may be more broad, but I have not encountered this with the C++ Project import nor text files. Tested using CTR's Music Orchestra example, looking at the .chrp files.

**To Reproduce**
1. Clone https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages.git
2. Open `Java Talon FX (Falcon 500)/Music - Orchestra` directory in 2021 WPILib VS Code editor
3. Click yes on prompt to import project into 2021, click Import Project button without editing any settings.
4. Diff song1.chrp in src/main/deploy of imported project to non-imported project. Binary files differ

**Expected behavior**
Binary files should be the same when importing.

Screenshot showing the two files in a hex editor.
![image](https://user-images.githubusercontent.com/28712271/103022838-bf8bab80-451a-11eb-9d50-46c8dfde5f71.png)

It appears to replace some bytes with the hex code `EF BF BD`.

Tested using WPILib_Windows64-2021.1.1-beta-4

**Comment by sciencewhiz** [comment]
I think this code is what's causing it. It's only in java and not c++.
https://github.com/wpilibsuite/vscode-wpilib/blob/master/vscode-wpilib/src/shared/generator.ts#L155-176

It's running on all files that match **/* https://github.com/wpilibsuite/vscode-wpilib/blob/master/vscode-wpilib/src/shared/generator.ts#L126-138

I think it should run only on .java and .gradle files.
