### ISSUE TITLE
Update Marketplace extension via CI during Github release

### ISSUE THREAD

**Issue by RyanHir** [wpilibsuite/vscode-wpilib#440]
Per https://marketplace.visualstudio.com/items?itemName=wpilibsuite.vscode-wpilib the current release is 2020.1.2 but the current release per this repo is 2021.2.2

**Comment by AustinShalit** [comment]
This should be fixed with a CI improvement to automatically publish the extension.

**Comment by ThadHouse** [comment]
We're not going to support this, and pushed a blank extension to the marketplace.
