### ISSUE TITLE
VSCode Trusted Workspaces Support

### ISSUE THREAD

**Issue by BrenekH** [wpilibsuite/vscode-wpilib#449]
The most recent update of VSCode (1.56.0) brings a feature called Workspace Trust into stable. If I understand correctly, this is meant to help mitigate a possible security issue from extensions executing code that is malicious. An example case would be a language server extension that runs code to provide its functionality.

The VSCode team recommends that even if extensions shouldn't be enabled in an untrusted workspace (which the default if the value in `package.json` is not set), they should still explicitly mark it as such.

More info is available in issue [#120251](https://github.com/microsoft/vscode/issues/120251#issuecomment-825832603) on the VSCode repository.

**Comment by sciencewhiz** [comment]
Fixed by #451, right?

**Comment by ThadHouse** [comment]
Correct.
