### ISSUE TITLE
Unable to install wpilib extension in VS Code 1.24.1

### ISSUE THREAD

**Issue by BrianAtlanta** [wpilibsuite/vscode-wpilib#46]
Error when installing VSIX:

Unable to install Extension 'wpifirst.vscode-wpilib-2019.0.0-alpha-4' as it is not compatible with Code '1.24.1'.

**Comment by BrianAtlanta** [comment]
Works in 1.25.1

**Comment by ThadHouse** [comment]
Vscode 1.25 is required. We need features older versions don't have. We will add to the docs though.
