### ISSUE TITLE
Creating new Java Template, results don't match documentation.

### ISSUE THREAD

**Issue by BrianAtlanta** [wpilibsuite/vscode-wpilib#47]
Options:
Template
Java
Timed Robot

Create new folder checked.

After creating project, and having VS Code opening the directory, I only have Robot.java.  The following are missing from my project:

Command Folder
subsystems Folder
OI.java
RobotMap.java

**Comment by BrianAtlanta** [comment]
I assume they should be there, since the documentation has an image that shows them.

**Comment by ThadHouse** [comment]
Those files only exist for the command based robot type. Let me look in the docs where it shows those are supposed to be there.

**Comment by BrianAtlanta** [comment]
The image under Building and Deploying Robot Code

**Comment by ThadHouse** [comment]
Yeah the screen capture just shows an example of what is there if you do a command style. Eclipse docs did the same thing.

**Comment by BrianAtlanta** [comment]
Yeah, I would say it's a 'me' issue.  Can't have every option shown.
