### ISSUE TITLE
Don't use debug JNI for simulation

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/vscode-wpilib#475]
https://github.com/wpilibsuite/vscode-wpilib/blob/331034483474b2e92318e61789ca78f793bcc392/vscode-wpilib/src/java/deploydebug.ts#L186

Without VS installed, this doesn't work. And the only way to get the debug dependencies is to install full VS. The redistributable doesn't solve the problem.

**Comment by PeterJohnson** [comment]
Fixed by #480.
