### ISSUE TITLE
Online Vendor Dependency Not Working

### ISSUE THREAD

**Issue by mdurrani808** [wpilibsuite/vscode-wpilib#507]
To Reproduce:
Create a new Java example project (type does not matter), go to the command pallet, manage vendor libraries, Install vendor libraries (online), and then use this link https://maven.photonvision.org/repository/internal/org/photonvision/PhotonLib-json/1.0/PhotonLib-json-1.0.json. Most of the time, when you click enter, nothing will happen and the .json file does not show up. The expected behavior is a dialogue showing up telling me that I should build and the appropriate .json file will show up. 

This has happened on a variety of systems.

Is this a VS Code Extension issue or a link issue?

**Comment by ThadHouse** [comment]
Which vscode-wpilib plugin version?

**Comment by BrenekH** [comment]
Is this perhaps related to #497? I believe the fix is already in the latest beta build.

**Comment by mdurrani808** [comment]
> Which vscode-wpilib plugin version?

Project Version: 2021.3.1
Extension Version: 2021.1.2

> Is this perhaps related to #497? I believe the fix is already in the latest beta build.

I will look into if we use that, I had not seen that before.

**Comment by mdurrani808** [comment]
Just checked, we do use Let's Encrypt. Will the fix be in place for the 2022 season?

**Comment by ThadHouse** [comment]
Yeah 2022 projects will have a workaround for letsencrypt repos.

**Comment by PeterJohnson** [comment]
Closing as duplicate.

**Comment by sciencewhiz** [comment]
I'm not sure that this is fixed. In beta 4, I get the following: 
![image](https://user-images.githubusercontent.com/4885091/147834196-943e93e0-6693-4449-b306-a65b3ea27eb9.png)

At least it shows an error message now.

**Comment by ThadHouse** [comment]
You need to create a new project with beta 4. The fix is in the templates.

**Comment by sciencewhiz** [comment]
This was with a new project with beta 4, with the fix in settings.json
