### ISSUE TITLE
#include errors on C++ Iterative Robot (following ScreenSteps)

### ISSUE THREAD

**Issue by drewwhis** [wpilibsuite/vscode-wpilib#51]
I have followed the steps up to and including http://wpilib.screenstepslive.com/s/currentCS/m/79833/l/932465-creating-a-new-wpilib-project-in-vs-code#c-configurations-c-only to create an iterative C++ robot project. It looks like I'm having issues with includes, but adding the includes directory(ies) in my /usr directory does not appear to resolve the issue.

Environment
* 2018 MacBook Pro on macOS High Sierra 10.13.6 (17G2208)
* Eclipse Photon, C++ Toolchains, FRC Plugins for Eclipse (installed prior to alpha)
* Xcode 9.4.1 and Xcode command line tools (installed prior to alpha)
* VS Code Version 1.25.1 (1.25.1) (installed prior to alpha)
* WPI Plugin: vscode-wpilib-2019.0.0-alpha-4.vsix

Messages generated:
* #include errors detected. Please update your includePath. IntelliSense features for this translation unit (/Users/drewwhis/Documents/FRC/sample-vs-code-bot/my-itr-cpp-bot/src/main/include/Robot.h) will be provided by the Tag Parser.
* cannot open source file "thread" (dependency of "IterativeRobot.h") 
* cannot open source file "memory" (dependency of "SmartDashboard/SendableChooser.h")
* cannot open source file "string"

Files
* [c_cpp_properties.json (.txt for upload)](https://github.com/wpilibsuite/vscode-wpilib/files/2229770/c_cpp_properties.txt)
* [output.txt](https://github.com/wpilibsuite/vscode-wpilib/files/2229776/output.txt)

Other
* Similar issue when creating/building a C++ command robot. 
* No errors when creating a Java robot.

**Comment by ThadHouse** [comment]
In the build folder, you should have a file called `vscodeconfig.json`. Can you post that please? If that doesn't exist, when you reopen the project it should give you a popup asking to setup configurations, make sure to click yes on that. Also, delete the `c_cpp_properties.json` file, as it gets in the way and can cause weird errors.

**Comment by drewwhis** [comment]
Here is the vscode config file. I remove the properties.json, restarted vscode and attempted a build, but had the same results.

[txt copy of vscodeconfig.json](https://github.com/wpilibsuite/vscode-wpilib/files/2229815/vscodeconfig.txt)

**Comment by ThadHouse** [comment]
Oh. Is the build failing, or just intellisense?

**Comment by drewwhis** [comment]
Both.

**Comment by ThadHouse** [comment]
What are the errors the build are giving? Likely if build is failing the roboRIO compiler is not set up properly.

**Comment by drewwhis** [comment]
This time the build is failing. IntelliSense appears to be working (no green squiggles at least). There's no RIO. The Java project is building fine with no RIO. The build error is

> > Task :compileFrcUserProgramExecutableFrcUserProgramCpp FAILED
In file included from /Users/drewwhis/Documents/FRC/sample-vs-code-bot/my-itr-cpp-bot/src/main/cpp/Robot.cpp:8:0:
/Users/drewwhis/Documents/FRC/sample-vs-code-bot/my-itr-cpp-bot/src/main/include/Robot.h:10:18: fatal error: string: No such file or directory
compilation terminated.

**Comment by ThadHouse** [comment]
Ok. So the compiler is not installed correctly. Can you send the options.txt file that is in the same folder you found that output.txt?

**Comment by ThadHouse** [comment]
Ok, so that definitely means something is wrong with your compiler install. Can you try creating a project in eclipse and seeing if that builds properly?

**Comment by drewwhis** [comment]
I am getting the same error there. I notice that by C++ build settings (Project>C/C++ Build>Tool Chain Editor>Current toolchain) default to Cross GCC and changing to MacOSX GCC resolves that issue but generates a different set of build errors.

**Comment by ThadHouse** [comment]
Switching to Mac GCC is definitely going to error, as the build specifically needs to cross build. But something is definitely wrong with your compiler in that case. Have you restarted since installing the compiler (We've seen on mac that occasionally breaks things if a reboot hasn't happened). If that doesn't work, can you try reinstalling the compiler?

**Comment by drewwhis** [comment]
Yes, I restarted a few days after installing the compiler. I'll try reinstalling.

**Comment by drewwhis** [comment]
I reinstalled with no changes. Here is the version information I get from gcc and g++ in /usr/bin, and those are the compilers that are called from my command line on my path.

> Lawrences-MBP:bin drewwhis$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

> Lawrences-MBP:bin drewwhis$ ./g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ThadHouse** [comment]
Can you get those outputs from the roboRIO compiler? `arm-frc-linux-gnueabi-gcc` and `arm-frc-linux-gnueabi-g++`

And also, can you search for the string header in the following location?
`/usr/local/arm-frc-linux-gnueabi`

**Comment by drewwhis** [comment]
I see the string header in /usr/local/arm-frc-linux-gnueabi/include/c++/5.5.0

gcc gives
> Lawrences-MBP:bin drewwhis$ arm-frc-linux-gnueabi-gcc --version
arm-frc-linux-gnueabi-gcc (GCC for FRC) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ gives
> Lawrences-MBP:bin drewwhis$ arm-frc-linux-gnueabi-g++ --version
arm-frc-linux-gnueabi-g++ (GCC for FRC) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ThadHouse** [comment]
Ok. 1 more thing to try. Can you run the following command and print the output? 

`arm-frc-linux-gnueabi-g++ -xc++ -E -v  -fsyntax-only  .`

**Comment by drewwhis** [comment]
> Lawrences-MBP:bin drewwhis$ arm-frc-linux-gnueabi-g++ -xc++ -E -v -fsyntax-only .
Using built-in specs.
COLLECT_GCC=arm-frc-linux-gnueabi-g++
Target: arm-frc-linux-gnueabi
Configured with: ../gcc-5.5.0/configure --enable-threads=posix --target=arm-frc-linux-gnueabi --with-cpu=cortex-a9 --with-float=softfp --with-fpu=vfpv3 --with-specs='%{save-temps: -fverbose-asm} %{funwind-tables|fno-unwind-tables|mabi=*|ffreestanding|nostdlib:;:-funwind-tables}' --enable-languages=c,c++ --enable-shared --enable-lto --disable-nls --with-pkgversion='GCC for FRC' --with-cloog --disable-multilib --disable-multiarch --prefix=/usr/local --with-sysroot=/usr/local/arm-frc-linux-gnueabi --enable-poison-system-directories --disable-libmudflap --with-build-sysroot=/usr/local/arm-frc-linux-gnueabi --with-system-zlib : (reconfigured) ../gcc-5.5.0/configure --enable-threads=posix --target=arm-frc-linux-gnueabi --with-cpu=cortex-a9 --with-float=softfp --with-fpu=vfpv3 --with-specs='%{save-temps: -fverbose-asm} %{funwind-tables|fno-unwind-tables|mabi=*|ffreestanding|nostdlib:;:-funwind-tables}' --enable-languages=c,c++ --enable-shared --enable-lto --disable-nls --with-pkgversion='GCC for FRC' --with-cloog --disable-multilib --disable-multiarch --prefix=/usr/local --with-sysroot=/usr/local/arm-frc-linux-gnueabi --enable-poison-system-directories --disable-libmudflap --with-build-sysroot=/usr/local/arm-frc-linux-gnueabi --with-system-zlib
Thread model: posix
gcc version 5.5.0 (GCC for FRC) 
COLLECT_GCC_OPTIONS='-E' '-v' '-fsyntax-only' '-shared-libgcc' '-mcpu=cortex-a9' '-mfloat-abi=softfp' '-mfpu=vfpv3' '-mtls-dialect=gnu' '-funwind-tables'
 /usr/local/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/cc1plus -E -quiet -v -D_GNU_SOURCE . -mcpu=cortex-a9 -mfloat-abi=softfp -mfpu=vfpv3 -mtls-dialect=gnu -fsyntax-only -funwind-tables
ignoring nonexistent directory "/usr/local/lib/gcc/../../arm-frc-linux-gnueabi/include/c++/5.5.0"
ignoring nonexistent directory "/usr/local/lib/gcc/../../arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi"
ignoring nonexistent directory "/usr/local/lib/gcc/../../arm-frc-linux-gnueabi/include/c++/5.5.0/backward"
ignoring nonexistent directory "/usr/local/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include"
ignoring nonexistent directory "/usr/local/arm-frc-linux-gnueabi/usr/local/include"
ignoring nonexistent directory "/usr/local/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include-fixed"
ignoring nonexistent directory "/usr/local/lib/gcc/../../arm-frc-linux-gnueabi/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/arm-frc-linux-gnueabi/usr/include
End of search list.
cc1plus: fatal error: .: No such file or directory
compilation terminated.

**Comment by ThadHouse** [comment]
Do any of those directories it says are non existant exist?

**Comment by drewwhis** [comment]
It does not appear that any of them exist.

**Comment by AustinShalit** [comment]
What happens when you run `xcode-select --install` in a terminal window and follow the prompts?

**Comment by drewwhis** [comment]
I get the "already installed" error (since I've already installed them).

**Comment by AustinShalit** [comment]
Do you have this directory?
`/usr/local/arm-frc-linux-gnueabi/include/c++/5.5.0`

If you don't, how much of that path exists?

**Comment by drewwhis** [comment]
Yup, full directory.

**Comment by AustinShalit** [comment]
Who is the owner of the /usr/local/arm-frc-linux-gnueabi directory?

**Comment by drewwhis** [comment]
root

**Comment by AustinShalit** [comment]
What does this print?

`pkgutil --only-files --files edu.wpi.first.frc-toolchain`

**Comment by AustinShalit** [comment]
Also this one please:

`pkgutil --pkg-info edu.wpi.first.frc-toolchain`

**Comment by drewwhis** [comment]
The first prints this list.
[output.txt](https://github.com/wpilibsuite/vscode-wpilib/files/2230194/output.txt)

The second prints
> Lawrences-MBP:local drewwhis$ pkgutil --pkg-info edu.wpi.first.frc-toolchain
package-id: edu.wpi.first.frc-toolchain
version: 2015.103
volume: /
location: 
install-time: 1532224382

**Comment by AustinShalit** [comment]
I am not sure what is going on but on a clean computer (just installed OS X 10.13.6 to a parallels image) I do not see this issue.

**Comment by AustinShalit** [comment]
How did you install the toolchains?  Can you upload the pkg file here?

**Comment by drewwhis** [comment]
I used the 2018 OSX tar here http://first.wpi.edu/FRC/roborio/toolchains/

**Comment by ThadHouse** [comment]
We have one more thing to try. GradleRIO can also grab a toolchain. The only downside is that will not work with eclipse, but should work just fine with vscode. Run the following commands from the directory with your gradlerio project

`./gradlew installToolchain`

then run 

`./gradlew generateVsCode`

Then try to build.

**Comment by drewwhis** [comment]
I had a successful build after that! But I'm getting IntelliSense errors again.

**Comment by ThadHouse** [comment]
Hmm ok. That file should have been different.  that tells us we have an issue.  Can you try something for me then.  Replace the vscodeconfig.json with this one. And don't rerun the generateVsCode task.

[vscodeconfig.txt](https://github.com/wpilibsuite/vscode-wpilib/files/2230449/vscodeconfig.txt)

**Comment by drewwhis** [comment]
Now I'm building successfully, and I do not see any IntelliSense errors.

**Comment by ThadHouse** [comment]
Cool. So that is actually issue in the plugin that generate the vscodeconfig.son file. I'll look into that. But things should stay working for now. Glad theyre working. We'll keep this open for now.

**Comment by drewwhis** [comment]
I'm going to try a clean install tomorrow and see if I get any similar errors.

**Comment by ThadHouse** [comment]
Ok. When you try that, I pushed an update that should fix the intellisense issue. To use it, in your build.gradle file, increase the version of the `GradleVsCode` plugin to `0.4.2`. This should fix needing the custom vscodeconfig.json file.

**Comment by drewwhis** [comment]
I've gone through with the clean install, and I'm still in the process of testing. I haven't installed a JDK yet (and building is requiring one). Is there any limitation on which versions of the JDK are expected to work? I didn't notice any in the steps (nor did I see it as a requirement).

**Comment by ThadHouse** [comment]
Anything between 8 and 10 should work, and we're wanting you to test anuthing so we know

**Comment by Ewpratten** [comment]
I get the same problem on Ubuntu 18.04 running the Ubuntu 17.04 toolchain

**Comment by ThadHouse** [comment]
It seems like this was resolved. I'm going to close it. If an issue like this happens again in beta we will want a new issue.
