### ISSUE TITLE
Manage Vendor Libraries - Check for updates (online) gives an error on Mac and Windows

### ISSUE THREAD

**Issue by aheidorn** [wpilibsuite/vscode-wpilib#516]
**Describe the bug**
After installing and reinstalling wpilib Kickoff Release, clicking Manage Vendor Libraries -> Check for updates (online) gives the following error message on both Mac and Windows:

Command 'WPILib: Manage Vendor Libraries' resulted in an error (Only absolute URLs are supported)

I've tried uninstalling all software from previous years, using a new machine and both macOS 11.6.2 and Windows 10 machines. Note, this was working on the mac using 2022 beta3 and beta4. I did not get around to installing rc1 and went straight to the official kickoff version.
 

**To Reproduce**
1. Follow instructions to install wpilib and vscode from distribution. Use the install for single user and inline install of vscode options in the wpilib installer.
2. Launch wpilib version of vscode. Go through look and feel setup. Restart after it says it installed extensions.
3. Create new project (I created the TankDrive example). 
4. Select Manage Vendor Libraries - Check for Updates (online)
5. Get the modal error box that says: "Command 'WPILib: Manage Vendor Libraries' resulted in an error (Only absolute URLs are supported) <Ok>"

**Expected behavior**
I expected a message in the status area that says no updates were found instead of an error box.

**Screenshots**

**Desktop (please complete the following information):**
 - WPILib Version: 2022.1.1
 - OS: macOS 11.6.2 and Windows 10

**Additional context**
Check for WPILib Updates seems to work, also Manage Vendor Libraries - Install new libraries (online) seems to work as well. I've also tried the other options and they seem to work - just the update (online) option seems broken.

<img width="1280" alt="Screen Shot 2022-01-10 at 12 14 37 AM" src="https://user-images.githubusercontent.com/19981992/148724841-f67f2878-cd78-49e7-aad2-041836510022.png">

**Comment by ThadHouse** [comment]
Yes, this is a known issue in the initial release, that will be fixed by #515
