### ISSUE TITLE
Update junit in templates to 4.13.1

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/vscode-wpilib#518]
The offline installer installs 4.13.1, but the gradle templates call out 4.12.

**Comment by sciencewhiz** [comment]
The gradleriobase in the installer calls out 4.12, so it seems more like an installer bug that it's pulling in 4.13.1

**Comment by ThadHouse** [comment]
Thats weird. That means something else has a transitive dependency on 4.13.1. Interesting.

**Comment by ThadHouse** [comment]
This has been fixed.
