### ISSUE TITLE
Font Issue in Terminal Window

### ISSUE THREAD

**Issue by Crossle86** [wpilibsuite/vscode-wpilib#533]
Hopefully this is the right place to post this question. I have been developing on Windows 7 and am now outfitting a Windows 10 system for WPILib devevlopment. I  use the Solarized Light theme. On Windows 7, when I build or deploy, the output in the terminal window (apparently from gradle) with bold text, is a black bold font. So this example output: * Get more help at https://help.gradle.org, that URL is bold and black.

On Windows 10, that same sample text is displayed as a VERY light gray, pretty much unreadable. I have looked for some setting that might change this and found nothing.

Another example: * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

On W7, --stacktrace is black. On W10, --stacktrace is such a light gray it can't be read.

This is affected by the theme to an extent. Selecting other light themes makes the text readable but still light gray in color. The improved readability appears to be come from the change in the background color.

Note that I said light gray for the text color, but in playing with other themes the color of bold text appears to be following the background color of the explorer pane of VSCode.

Are the theme font colors configurable somewhere? This only seems to be an issue in the terminal window. Code coloring works fine.

**Comment by Daltz333** [comment]
WPILib uses default font colors. We aren't directly manipulating any of that.

**Comment by Crossle86** [comment]
OK. Thanks.
