### ISSUE TITLE
Git instructions

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/vscode-wpilib#54]
We should add some screensteps on using git.

**Comment by Ewpratten** [comment]
it would be cool if they supported gitkracken in the screensteps. Nice, Simple way to do git.

**Comment by ThadHouse** [comment]
Any docs from us are likely to use the integrated VS Code git support. We don't want more programs to download for users that are just learning this stuff.

**Comment by kennethkau** [comment]
I'm currently working on documentation / learning material for the teams I mentor. It covers VS Code and I plan on discussing the integrated git / source control pane.
