### ISSUE TITLE
Trust project dialog doesn't pop up after creating project

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/vscode-wpilib#549]
After creating a project, the trust selection dialog doesn't come up, so the project isn't trusted. If you switch to another application and then back to VS Code, it does pop up.

**Comment by sciencewhiz** [comment]
This worked in VS Code 1.66.2, but doesn't in 1.67.2

**Comment by ThadHouse** [comment]
You can also click the VS Code icon in the menu to pop up the prompt too.

**Comment by ThadHouse** [comment]
I made an issue on VS Code https://github.com/microsoft/vscode/issues/165121

**Comment by sciencewhiz** [comment]
> You can also click the VS Code icon in the menu to pop up the prompt too.

What Icon? Can you show a picture? I tried clicking a few different things couldn't get it to pop up.

**Comment by ThadHouse** [comment]
I meant WPILib icon.
<img width="98" alt="Screenshot 2022-11-01 at 6 16 15 PM" src="https://user-images.githubusercontent.com/7727148/199371932-f5c863ff-5789-4f9e-bab2-a0c1ca4e95e7.png">

**Comment by sciencewhiz** [comment]
I get that the whole extension is disabled and no icon.

![image](https://user-images.githubusercontent.com/4885091/199373138-4d1af97c-c1dd-4e9c-add3-96ce31fdbabb.png)

**Comment by sciencewhiz** [comment]
Opening the project in a new window rather then a current window brings up the trust dialog box as expected
