### ISSUE TITLE
Create new project not automatically closing bottom panel showing prior build output.

### ISSUE THREAD

**Issue by JimTripi** [wpilibsuite/vscode-wpilib#553]
Starting operation to create a new project does not automatically close the bottom panel with the prior project's build output. This is different than the behavior observed last year. 

![Screenshot_20221103_034339](https://user-images.githubusercontent.com/9613821/199829884-d82db4ea-e460-473a-8f3b-e1f7b1d25c70.png)

**Comment by ThadHouse** [comment]
I just installed 2022 again, and it has this same behavior. Also, we don't control VS Code's handling of the terminal, so theres nothing actionable we could do here anyway.

**Comment by JimTripi** [comment]
Ok.  I don't recall having to dismiss it before, but I understand how you checked it.   I will close this then.
