### ISSUE TITLE
New project help occasionally pops up every time VS Code opens.

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/vscode-wpilib#56]
We are just using VS Codes internal storage for doing this, so potentially something is wrong on certain systems that causes this. 

@Ewpratten what OS are you using? Also, can you post a screenshot of which window, so I can be sure I'm thinking of the right one?

**Comment by Ewpratten** [comment]
I'm away from my computer. It is Ubuntu 18.04 running i3wm (if that matters at all) I am using an Ubuntu backport to 17.04 to get wpilib through apt. Also, I am using the Ubuntu 16.04 version of libmpfr4

**Comment by ThadHouse** [comment]
Does this still happen? I have a feeling this is a permissions issue on the upstream VS Code side, because we're just using a built in API for doing this. Can you try updating everything and seeing if that still happens. If not, I want to close this issue.

**Comment by Ewpratten** [comment]
I don't get this any more.

**Comment by ThadHouse** [comment]
Ok. Then I'm closing this.
