### ISSUE TITLE
visual bug: frc::LinearFilter and frc::PowerDistribution not found by intellisense

### ISSUE THREAD

**Issue by jon-bassi** [wpilibsuite/vscode-wpilib#574]
WPILIB v2023.1.1 

issue on both Mac and windows

including <frc/filter/LinearFilter.h> and <frc/PowerDistribution.h>
code builds/links fine - no errors
refreshing intellisense/reinstalling toolchain/deleting build directory doesn't fix

<img width="666" alt="image" src="https://user-images.githubusercontent.com/9029410/211162849-8cdae13c-0f37-4a54-923d-64f1315ab14f.png">

note: I can right click > goto Definition of the includes for LinearFilter and PowerDistribution and vscode will open up the headers just fine

**Comment by ThadHouse** [comment]
Something included in `#include "Eigen/QR"` is causing this. It seems to break any classes defined after that file is included. I'll look

**Comment by sciencewhiz** [comment]
Does it work if you add the following to the top of any file with intellisense errors?

```
#if __INTELLISENSE__
#undef __ARM_NEON
#undef __ARM_NEON__
#endif
```
