### ISSUE TITLE
FRC toolchain Ubuntu Major issue

### ISSUE THREAD

**Issue by Ewpratten** [wpilibsuite/vscode-wpilib#58]
The FRC c++ compiler (I don't remember the package name) requires libmpfr to be installed on the system (Linux). Libmpfr is no longer in apt and I think it no longer supports Ubuntu. This means that it will be impossible to install frc-toolchain in Ubuntu 18.04+ without using a xenial(16.04) backport.

**Comment by ThadHouse** [comment]
Once we have a native 18.04 compiler this will be fixed. That is not guaranteed to happen for the alpha though, and might not happen until the 2019 season.
