### ISSUE TITLE
#include errors when coding in C++

### ISSUE THREAD

**Issue by Macattack124** [wpilibsuite/vscode-wpilib#587]
So I am working on the robot and we are wanting to program using C/C++. We followed the steps on WPILIB to get started but we are noticing that we are getting #include errors. The main error we are getting is with #include <frc2/command/CommandPtr.h>. The error reads cannot open source file "frc2/command/CommandPtr.h. We are currenting using the 2022 version on WPILIB VS Code. We are able to use Java perfectly fine but we are getting these #include errors and do not know how to fix them. Will also upload the code that we currently have.
[Robot C.zip](https://github.com/wpilibsuite/vscode-wpilib/files/10807169/Robot.C.zip)

**Comment by PeterJohnson** [comment]
Are you having errors when building or just in intellisense?  If you’re having errors when building you are missing the commands vendor dep—you can pull this from creating a new command-based project.

**Comment by Macattack124** [comment]
When I build the robot code, I get this error: 
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':compileFrcUserProgramReleaseExecutableFrcUserProgramCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling Constants.cpp.
      C++ compiler failed while compiling ExampleSubsystem.cpp.
      C++ compiler failed while compiling RobotContainer.cpp.
      C++ compiler failed while compiling Robot.cpp.
  See the complete log at: file:///C:/Users/U220887/Desktop/ADAS%20Robot%20C++/Robot%20C/build/tmp/compileFrcUserProgramReleaseExecutableFrcUserProgramCpp/output.txt
   > C++ compiler failed while compiling Constants.cpp.
   > C++ compiler failed while compiling ExampleSubsystem.cpp.
   > C++ compiler failed while compiling RobotContainer.cpp.
   > C++ compiler failed while compiling Robot.cpp.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':compileFrcUserProgramDebugExecutableFrcUserProgramCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling Constants.cpp.
      C++ compiler failed while compiling ExampleSubsystem.cpp.
      C++ compiler failed while compiling RobotContainer.cpp.
      C++ compiler failed while compiling Robot.cpp.
  See the complete log at: file:///C:/Users/U220887/Desktop/ADAS%20Robot%20C++/Robot%20C/build/tmp/compileFrcUserProgramDebugExecutableFrcUserProgramCpp/output.txt
   > C++ compiler failed while compiling Constants.cpp.
   > C++ compiler failed while compiling ExampleSubsystem.cpp.
   > C++ compiler failed while compiling RobotContainer.cpp.
   > C++ compiler failed while compiling Robot.cpp.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by PeterJohnson** [comment]
Can you provide a link to your robot project (eg on github)?

**Comment by Macattack124** [comment]
Here is the github link: https://github.com/Macattack124/Robot-Test.git

**Comment by PeterJohnson** [comment]
Your code is still 2022.  You need to install 2023 and run the project importer to import the project to 2023 (or start a new 2023 project.

**Comment by Macattack124** [comment]
Is C not supported in 2022? I am confused by whey I would need to upgrade it?

**Comment by PeterJohnson** [comment]
You have to use a 2023 project to be compatible with the 2023 image, which is required for competition.  Also the include you are trying to use (CommandPtr) is new for 2023.
