### ISSUE TITLE
Vendor Library Menu in VScode extension (online install)

### ISSUE THREAD

**Issue by srimanachanta** [wpilibsuite/vscode-wpilib#592]
Living issue for [this](https://github.com/orgs/wpilibsuite/projects/12/views/1?filterQuery=online&pane=issue&itemId=23334196) 2024 priority.

The idea is as the title suggests, a menu in the VScode extension to install a vendordep json from a repository of vendor dependencies.

Firstly, this should be added after adding [this feature](https://github.com/wpilibsuite/GradleRIO/issues/640). A field will need to be created for a year/wpilib version either way, so doing it after that makes the most sense. Secondly, how do we want to manage the repository of vendor JSONs? Using just the live link seems like a bad idea because if the vendor changes the URL (such as Phoniex with the introduction of Phoniex PRO), this would be broken. Restricting vendors also seems like a poor idea. Maybe something like a nightly check of the JSONs and then saving those ourselves to be referenced by the extension?

**Comment by PeterJohnson** [comment]
My concept was this GitHub repo: https://github.com/wpilibsuite/vendor-json-repo

**Comment by sciencewhiz** [comment]
Fixed by #672
