### ISSUE TITLE
Add `gradle clean` to the VS Code Command List

### ISSUE THREAD

**Issue by bdaroz** [wpilibsuite/vscode-wpilib#667]
A number of times this year as CSA I had Java teams with weird crash issues, or references to classes that didn't exist in code pop up on the RoboRIO. All of these were the result of an outdated grade build directory and with a `gradle clean` and a redeploy were cleaned up. (Pun may or not be intended here.)

There is a menu option to run a specific gradle command, but can we add one to specifically clean the directory, and perhaps some docs on best practices for using it.

In the alternative, should we consider cleaning every build? (At the cost of compile time, especially for C++ teams)

**Comment by sciencewhiz** [comment]
Fixed by #668

**Comment by bdaroz** [comment]
Thank you!
