### ISSUE TITLE
Is there a way to update (or suggest changes to) the screensteps for vscode?

### ISSUE THREAD

**Issue by Ewpratten** [wpilibsuite/vscode-wpilib#67]
I am currently working on getting all of wpilibsuite to work on a chromebook.

So far, I have the following working:
 - gradlerio
 - vscode
 - frc-toolchain (with some hacky installation scripts)

and I would like to add these to the official installation instructions. But, I cant find how to do that. Are the screensteps a closed thing? if so, how should I go about getting the chromebook install instructions added? Is there some group that I need to be added to? 

Any pointers in the right direction would be greatly appreciated.

**Comment by PeterJohnson** [comment]
Screensteps are a closed thing.  We do consider suggestions for including additional information (and even entire writeups).  However, what is on screensteps is what we officially support, and as we have no plans at present to officially support use of chromebooks for robot code development, we will not be adding official installation instructions for that platform.  That being said, it's great that you want to share your efforts and lessons learned with other teams!  My recommendation would be to do an installation writeup and share it as a whitepaper on an unofficial forum such as Chief Delphi.

**Comment by Ewpratten** [comment]
Alright! Thank you!

I am going to create a repo (similar to toolchain-builder) for installation instructions if that's ok.

**Comment by Ewpratten** [comment]
Alright! Thank you!

I am going to create a repo (similar to toolchain-builder) for installation instructions if that's ok.
