### ISSUE TITLE
Python: WPILib VS Code incorrectly recommended upgrading Python project

### ISSUE THREAD

**Issue by daltzctr** [wpilibsuite/vscode-wpilib#697]
![Image](https://github.com/user-attachments/assets/083377b8-d576-4334-9561-5bd04620b24b)

**Comment by ThadHouse** [comment]
@daltzctr can you post the wpilib_preferences.json, so I can use that as reference?

**Comment by daltzctr** [comment]
```
{
  "teamNumber": 7762
}
```

**Comment by ThadHouse** [comment]
Ah. Thats why. It needs a year field.

`"projectYear": "2025Alpha",`

That's the flag that stops that popup. Should probably also add project Type too. And for now we'd probably just skip the upgrade prompt if the project type is python.

**Comment by daltzctr** [comment]
Hm. I think this was automatically generated by Python tooling when I set the team number using the robotpy commands
