### ISSUE TITLE
Upgrade of C++ Not Handling Includes

### ISSUE THREAD

**Issue by tcroots78** [wpilibsuite/vscode-wpilib#71]
Trying to to the WPILIP: Upgrade Eclipse for C++ from the screensteps. We had done some "Create Example Projects" from the previous page. This error looked a bit different from others with the Upgrade

For this we:
1. Cloned github repo
2. Ran Upgrade Command and selected the build
3. It pulled in all the code (yay)
4. It gives me the little pop-up that it IntelliSense isn't configured, but doesn't have a "Yes" (the example setup did). Instead it tells me "Configure your iItellisense to find missing headers" and a link to the online config help.

Also strange is that I have a /src/main/java folder, rather than /src/main/cpp (as in the examples). The examples seemed to put the WPILib setup in a vscodeconfig.json file under the build (I think).

New to gradle and still learning a ton in c++

**Comment by ThadHouse** [comment]
Hmm, it seems like it thought your project was Java, and not C++. Can you post a zip or a github link to the project you were attempting to upgrade?

**Comment by tcroots78** [comment]
hmm, that one was private, let me see if I can try a public one. just a sec.

**Comment by tcroots78** [comment]
ok, so this one worked better, https://github.com/FRC4967/2017-Switch. It imported as cpp and gave me the option. That was successful, but not getting include errors for .h files in the same directory as the .cpp (which I think I saw in another issue)

**Comment by ThadHouse** [comment]
Yeah that issue is fixed by this comment
https://github.com/wpilibsuite/vscode-wpilib/issues/57#issuecomment-410490853

**Comment by ThadHouse** [comment]
If that solved your issue then we can close this.

**Comment by tcroots78** [comment]
Oh, it is actually only the CANTalon.h class (it is actually inside all the included .h files. Hmmm. Did those come with the WPILib VSIX extension we installed?

**Comment by tcroots78** [comment]
I'm not seeing any other CANTalon issues out there and it isn't actually the .h files, but a message about an included.h file (the CANTalon), so is this different?

**Comment by ThadHouse** [comment]
Since that is a 2017 project you posted, CTRE's libraries changed for 2018. So you will need to change headers to what they used in 2018.

**Comment by tcroots78** [comment]
Hmmm again, I thought we had done that to get the 2017 guy working last year...used it for robot practice. I'll double check tomorrow.

Do you know where the included wpilib folder is? Think we needed that when upgrading to 2018 code

**Comment by ThadHouse** [comment]
Its in build/tmp/. You're going to have to search the directories.

**Comment by tcroots78** [comment]
ah, you're right. it's old. ok gotta update that. something for a different night. still unsure why the 2018 code came in as java, huh. Any idea what it looks at? I gotta ask some people if I can make public/post it.

**Comment by ThadHouse** [comment]
It looks for the existance of a .cproject file. It would have failed if it was actually a C++ project, as the Java project requires some things that don't exist in C++, and would have thrown an error. Posting the build.properties and the .cproject file should be enough for me to have a look, but the full project would be better.

**Comment by tcroots78** [comment]
oh, that's funny. that ended up getting put in our gitignore so it is only on last years local spots and this was a new clone b/c some students kept messing it up. we figured out how to fix it, but they preferred the ignore. ok, that should solve that. Thanks so much!

**Comment by ThadHouse** [comment]
No worries we're happy to see issues because even issues like this will help others troubleshoot and us write better docs.
