### ISSUE TITLE
Standalone utility not installed on macOS

### ISSUE THREAD

**Issue by ArchdukeTim** [wpilibsuite/vscode-wpilib#711]
After running through the installer, both skipping and not skipping installing vscode, the wpilibutility isn't installed into `~/wpilib/2025/utility` like it was in 2024

It was installed on windows

**Comment by rzblue** [comment]
Is there anything in that folder at all?

There's nothing special done for the standalone utility, the only install step is extracting the whole utility folder from the artifacts archive alongside the rest of the contents of the wpilib folder.

**Comment by sciencewhiz** [comment]
Intel or Apple Silicon?
