### ISSUE TITLE
"No C++ configurations. Yes to refresh." may be confusing

### ISSUE THREAD

**Issue by pgfisico** [wpilibsuite/vscode-wpilib#84]
This message may be confusing to users that don't understand that Gradle is providing project information to VS Code.

Instead, it should explain the problem and why refreshing is needed, or maybe even do it automatically.

https://github.com/wpilibsuite/vscode-wpilib/blob/cc47d12a97c2c2fd6b709c471ec820f2f1fdbd74/vscode-wpilib/src/cppprovider/apiprovider.ts#L77

**Comment by ThadHouse** [comment]
It we put any more information it truncates the message which is even worse. We're just going to have to explain this in documentation. Automatically isn't really an option for a multitude of reasons both on the gradlerio and the vscode side.

**Comment by ThadHouse** [comment]
I updated the documentation, and made refreshing more often to occur.
