### ISSUE TITLE
Eclipse Import does not preserve all files

### ISSUE THREAD

**Issue by pgfisico** [wpilibsuite/vscode-wpilib#85]
Importing an eclipse project does not keep all the files. For example directories like .git, .svn, lib, and others.

**Comment by ThadHouse** [comment]
We explicitly don't want this behavior. We want it to be a new project, where just the old code is included. Any custom libs or anything we can't import anyway. This was the requested behavior by most people asked.

**Comment by pgfisico** [comment]
It might be nice to preserve VCS files, but this may not be an issue depending on the intent of the import function.

Is the import just intended for easy testing for 2019 alpha/beta? Will it go away in 2020?

When creating new projects, none of these things should be an issue. It may be possible to parse the eclipse project XML, but it's probably not worth it depending on what the feature is intended as.

**Comment by ThadHouse** [comment]
Vcs explicitly we don't want. It's wanted to be a new project. Same reason we don't allow importing into the same folder.

Yes the functionality will go away in 2020. It will likely be an import 2019 project at that point.

It is a definite no go on parsing project xml. Way too much to go wrong, and anyone that customized that can likely repeat it.
