### ISSUE TITLE
Unknown Crashed when deploy on Mac OS X

### ISSUE THREAD

**Issue by WuYuanhun** [wpilibsuite/vscode-wpilib#88]
When trying to deploy on a Max platform, unknown error will occurred , crashing the whole system.
Already happened for several times on two different MBPs.
Trying to provide more details.
Thanks.

**Comment by ThadHouse** [comment]
I'm definitely going to need more information. I have no clue what could be causing this without that. Does anything print out in the task window, or just it just crash as soon as you hit the button?

**Comment by WuYuanhun** [comment]
> I'm definitely going to need more information. I have no clue what could be causing this without that. Does anything print out in the task window, or just it just crash as soon as you hit the button?

Just crash as soon as the deploy button is hit

**Comment by WuYuanhun** [comment]
Sometimes, crashing may also happen randomly when the Robotrio is wire-connected. (This may be another issue.) 
What I am sure  is that it will crash as soon as deploy button is hit on a Mac.

**Comment by ThadHouse** [comment]
That definitely sounds like a hardware issue, especially if the Mac is crashing. Can you check the Mac error logs and see what it's saying. Everything of ours in code that is very unlikely to hard crash the operating system.

**Comment by WuYuanhun** [comment]
Not available right now.
Maybe in 10H.
Thanks

**Comment by ThadHouse** [comment]
The other thing is try running `./gradlew build` from the command line in your project directly. You can open one in VS Code with `cmd + ~`

**Comment by WuYuanhun** [comment]
> The other thing is try running `./gradlew build` from the command line in your project directly. You can open one in VS Code with `cmd + ~`

Build successful when  using `./gradlew build`

**Comment by ThadHouse** [comment]
Interesting. That means something in vs code is failing, and since I do very little during the deploy button, it's likely failing on vs codes side. So I'm going to need a video to do any more debugging.

**Comment by ThadHouse** [comment]
Does this still happen on newer versions of VS Code? I can't really debug anything currently, as I can't reproduce anything similar to this.

**Comment by WuYuanhun** [comment]
Problem solved via updating to the latest version.
Sorry for no replying for a long time. = . =
Thanks.
