### ISSUE TITLE
AndyMark LED Controller

### ISSUE THREAD

**Issue by tcroots78** [wpilibsuite/vscode-wpilib#92]
Trying to use our code from last year that has https://www.andymark.com/product-p/am-3847.htm and we get errors in the main LightDrive.h that is provided (the one they provide) in the downloads and it has instructions for installing it.

Instead of putting it in the includes, we had just dropped it in with our Robot code last year and that seemed to work. Although I think I remember eclipse complaining about some stuff...but it compiled and worked...and was during build season...so we never quite prioritized it 😲 

The instructions also mention putting files into the wpilib/user/cpp/lib directory...which I think we needed to do, but not sure how to do that now with these pulling in through gradle.

**Comment by tcroots78** [comment]
Played around a bit trying to see what includes and libs were being accessed

I was able to get IntelliSense working by putting the LightDrive.h and LightDriveCAN.h files in 
/Library/Developer/CommandLineTools/usr/include/c++/v1

but no joy in getting the build to work tried putting the libMachLib.a in either:
/usr/local/arm-frc-linux-gnueabi/lib
/usr/local/arm-frc-linux-gnueabi/usr/lib
(and .h in the related include)

**Comment by ThadHouse** [comment]
Thats definitely not where you want to put either of those. Basically to make things work you're going to need to add things to your build.gradle file to manually link that binary. It might be better to move this over to the GradleRIO repo as this more pertains to that. GradleRIO handles the build.

**Comment by AustinShalit** [comment]
I am going to move this issue over to GradleRIO because it is a GradleRIO documentation issue.

**Comment by AustinShalit** [comment]
This issue was moved to wpilibsuite/GradleRIO#186
