### ISSUE TITLE
Commands running from command palette fail to run

### ISSUE THREAD

**Issue by MatthewBehnke** [wpilibsuite/vscode-wpilib#98]
I changed the plugin from alpha-4 to beta0-pre1
When I tired to run commands from the command palette the command fails this is the same for all of the other commands

**Comment by ThadHouse** [comment]
Don't update to beta0-pre1. I need to delete it. And what's happening is beta won't install over alpha, so you'll manually need to uninstall alpha when we do beta.

**Comment by ThadHouse** [comment]
Note unless you are a beta team, you will not have access to the roborio image required for beta. Even if we have betas on here, they will not be usable for robot code.
